---
title: "p8105_hw1_sc4934"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r chunk_library, echo=FALSE, results = "hide", message = FALSE} 
library(ggplot2)
library(tidyverse)
```



# Problem 1

```{r chunk_load_data}
data("penguins", package = "palmerpenguins")
```

## description: 
The penguins data set contains 8 variables. The variables contain information on individual penguins, including the species, island where they are located, bill length in mm, bill depth in mm, etc. 

There are 344 rows `nrow` and 8 columns `ncol` in the data set.

The mean flipper length is 200.9152 mm. 

```{r chunk_mean }
mean(penguins$flipper_length_mm, na.rm = TRUE)
```


## Scatter Plot: 

```{r chunk_scatterplot, message = FALSE, warning=FALSE}
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
ggsave ("scatter_plot.pdf")

```


# Problem 2

## dataframe:
```{r chunk_dataframe}
df <- tibble(
  var_norm = rnorm(n=10),
  var_logic = var_norm > 0,
  var_char = c("one", "two","three","four","five","six","seven","eight","nine","ten"),
  var_fac = factor(c("low","medium","high","low","medium","high","low","medium","high", "low" ))
  )

mean(df$var_norm)
mean(df$var_logic)
mean(df$var_char)
mean(df$var_fac)


```



